// ============================================================
// Phase 5 tests: DBML Generator (SchemaIR → DBML string)
// ============================================================

import { describe, it, expect } from 'bun:test';
import { generateDbml, type DbmlWriterOptions } from '../src/generator/dbml-writer.js';
import { parseDbml } from '../src/parser/dbml-parser.js';
import type {
  SchemaIR,
  TableDefinition,
  ColumnDef,
  IndexDef,
  FKDef,
  TriggerDef,
  ViewDef,
  ProcedureDef,
  EnumDef,
  DbsExtension,
} from '../src/core/types.js';

// ============================================================
// Helpers
// ============================================================

/** Minimal valid SchemaIR with no content */
function emptySchema(): SchemaIR {
  return { tables: [], views: [], procedures: [], enums: [], extensions: [] };
}

/** Create a basic column */
function col(overrides: Partial<ColumnDef> = {}): ColumnDef {
  return {
    name: 'id',
    type: 'integer',
    nullable: false,
    primaryKey: true,
    unique: false,
    autoIncrement: true,
    ...overrides,
  };
}

/** Create a basic table */
function table(overrides: Partial<TableDefinition> = {}): TableDefinition {
  return {
    name: 'users',
    columns: [col()],
    indexes: [],
    foreignKeys: [],
    triggers: [],
    ...overrides,
  };
}

// ============================================================
// Tests: generateDbml — basic output
// ============================================================

describe('generateDbml', () => {
  // --- Empty schema ---

  it('should produce minimal output for empty schema', () => {
    const result = generateDbml(emptySchema());
    expect(result).toBe('\n');
  });

  it('should end with a single newline (no trailing blank line)', () => {
    const result = generateDbml(emptySchema());
    const lines = result.split('\n');
    // Last element is empty (split on trailing \n), previous is also empty
    expect(result.endsWith('\n')).toBe(true);
    expect(result).toBe('\n'); // exactly one newline
  });

  // --- Project block ---

  it('should generate a Project block when options are provided', () => {
    const opts: DbmlWriterOptions = {
      projectName: 'my_project',
      databaseType: 'SQLite',
    };
    const result = generateDbml(emptySchema(), opts);
    expect(result).toContain('Project my_project {');
    expect(result).toContain("  database_type: 'SQLite'");
    expect(result).toContain('}');
  });

  it('should include Project Note when provided', () => {
    const opts: DbmlWriterOptions = {
      projectName: 'test',
      projectNote: 'Generated by db-sync',
    };
    const result = generateDbml(emptySchema(), opts);
    expect(result).toContain("  Note: 'Generated by db-sync'");
  });

  it('should skip Project block when no options provided', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [table()],
    };
    const result = generateDbml(schema);
    expect(result).not.toContain('Project');
  });

  // --- Simple table ---

  it('should generate a basic table with columns', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'users',
          columns: [
            { name: 'id', type: 'integer', nullable: false, primaryKey: true, unique: false, autoIncrement: true },
            { name: 'email', type: 'varchar(255)', nullable: false, primaryKey: false, unique: true, autoIncrement: false },
            { name: 'name', type: 'varchar(100)', nullable: false, primaryKey: false, unique: false, autoIncrement: false },
          ],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('Table users {');
    expect(result).toContain('  id integer [pk, increment, not null]');
    expect(result).toContain('  email varchar(255) [not null, unique]');
    expect(result).toContain('  name varchar(100) [not null]');
    expect(result).toContain('}');
  });

  // --- Nullable column ---

  it('should output [null] for nullable columns', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'posts',
          columns: [
            col({ name: 'id' }),
            { name: 'body', type: 'text', nullable: true, primaryKey: false, unique: false, autoIncrement: false },
          ],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('body text [null]');
  });

  // --- Default values ---

  it('should format default values correctly', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'test',
          columns: [
            col({ name: 'id' }),
            { name: 'role', type: 'varchar(20)', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: 'user' },
            { name: 'created_at', type: 'timestamp', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: '`now()`' },
            { name: 'count', type: 'integer', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: '0' },
            { name: 'deleted', type: 'boolean', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: 'false' },
            { name: 'nothing', type: 'text', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: 'NULL' },
          ],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain("default: 'user'");
    expect(result).toContain('default: `now()`');
    expect(result).toContain('default: 0');
    expect(result).toContain('default: false');
    expect(result).toContain('default: null');
  });

  // --- Column note (comment) ---

  it('should output [note: ...] when column has a comment', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'users',
          columns: [
            col({ name: 'id', comment: 'Primary key' }),
          ],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain("note: 'Primary key'");
  });

  // --- Indexes ---

  it('should generate Indexes block for single-column index', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'users',
          columns: [col()],
          indexes: [
            { name: 'idx_email', columns: ['email'], unique: true },
          ],
          foreignKeys: [],
          triggers: [],
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('Indexes {');
    expect(result).toContain("  email [unique, name: 'idx_email']");
    expect(result).toContain('  }');
  });

  it('should generate Indexes block for composite index', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'users',
          columns: [col()],
          indexes: [
            { name: 'idx_name_city', columns: ['name', 'city'], unique: false, type: 'btree' },
          ],
          foreignKeys: [],
          triggers: [],
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('Indexes {');
    expect(result).toContain("  (name, city) [name: 'idx_name_city']");
    // btree is default, should NOT appear
    expect(result).not.toContain('type: btree');
    expect(result).toContain('  }');
  });

  it('should output index type when non-btree', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'users',
          columns: [col()],
          indexes: [
            { name: 'idx_hash', columns: ['token'], unique: false, type: 'hash' },
          ],
          foreignKeys: [],
          triggers: [],
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('type: hash');
  });

  it('should skip Indexes block when table has no indexes', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'simple',
          columns: [col()],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).not.toContain('Indexes');
  });

  // --- Foreign Keys (Refs) ---

  it('should generate Ref for foreign key', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'posts',
          columns: [
            col({ name: 'id' }),
            { name: 'user_id', type: 'integer', nullable: false, primaryKey: false, unique: false, autoIncrement: false },
          ],
          indexes: [],
          foreignKeys: [
            {
              name: 'fk_posts_user',
              columns: ['user_id'],
              refTable: 'users',
              refColumns: ['id'],
              onDelete: 'cascade',
            },
          ],
          triggers: [],
        },
        table({ name: 'users' }),
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('Ref: posts.user_id > users.id [delete: cascade]');
  });

  it('should generate Ref with onDelete and onUpdate', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'items',
          columns: [
            col({ name: 'id' }),
            { name: 'category_id', type: 'integer', nullable: false, primaryKey: false, unique: false, autoIncrement: false },
          ],
          indexes: [],
          foreignKeys: [
            {
              name: 'fk_category',
              columns: ['category_id'],
              refTable: 'categories',
              refColumns: ['id'],
              onDelete: 'set null',
              onUpdate: 'cascade',
            },
          ],
          triggers: [],
        },
        table({ name: 'categories' }),
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('Ref: items.category_id > categories.id [delete: set null, update: cascade]');
  });

  it('should handle composite foreign keys', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'order_items',
          columns: [
            col({ name: 'id' }),
            { name: 'order_id', type: 'integer', nullable: false, primaryKey: false, unique: false, autoIncrement: false },
            { name: 'product_id', type: 'integer', nullable: false, primaryKey: false, unique: false, autoIncrement: false },
          ],
          indexes: [],
          foreignKeys: [
            {
              name: 'fk_order_product',
              columns: ['order_id', 'product_id'],
              refTable: 'products',
              refColumns: ['order_ref', 'product_ref'],
            },
          ],
          triggers: [],
        },
        table({ name: 'products' }),
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain(
      'Ref: order_items.(order_id, product_id) > products.(order_ref, product_ref)',
    );
  });

  // --- Enums ---

  it('should generate Enum blocks', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      enums: [
        { name: 'user_role', values: ['admin', 'editor', 'viewer'] },
        { name: 'status', values: ['active', 'inactive'] },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('Enum user_role {');
    expect(result).toContain('  admin');
    expect(result).toContain('  editor');
    expect(result).toContain('  viewer');
    expect(result).toContain('}');
    expect(result).toContain('Enum status {');
    expect(result).toContain('  active');
    expect(result).toContain('  inactive');
  });

  // --- Triggers as @dbs comments ---

  it('should generate @dbs:trigger comments for table triggers', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'users',
          columns: [col()],
          indexes: [],
          foreignKeys: [],
          triggers: [
            {
              name: 'after_insert_users',
              timing: 'after',
              event: 'insert',
              body: 'CREATE TRIGGER after_insert_users\nAFTER INSERT ON users\nFOR EACH ROW\nBEGIN\n  INSERT INTO audit_log (action) VALUES (\'INSERT\');\nEND;',
            },
          ],
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('// @dbs:trigger:after_insert_users:users:after:insert');
    expect(result).toContain('// CREATE TRIGGER after_insert_users');
    expect(result).toContain("//   INSERT INTO audit_log (action) VALUES ('INSERT');");
  });

  // --- Views as @dbs comments ---

  it('should generate @dbs:view comments', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      views: [
        {
          name: 'active_users',
          definition: 'CREATE VIEW active_users AS\nSELECT id, name FROM users WHERE active = 1;',
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('// @dbs:view:active_users');
    expect(result).toContain('// CREATE VIEW active_users AS');
    expect(result).toContain('// SELECT id, name FROM users WHERE active = 1;');
  });

  // --- Procedures as @dbs comments ---

  it('should generate @dbs:procedure comments', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      procedures: [
        {
          name: 'cleanup_old_posts',
          body: 'CREATE PROCEDURE cleanup_old_posts(IN days_old INT)\nBEGIN\n  DELETE FROM posts WHERE created_at < DATE_SUB(NOW(), INTERVAL days_old DAY);\nEND;',
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('// @dbs:procedure:cleanup_old_posts');
    expect(result).toContain('// CREATE PROCEDURE cleanup_old_posts');
    expect(result).toContain('//   DELETE FROM posts');
  });

  // --- Raw extensions ---

  it('should generate @dbs:raw extensions at top level', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      extensions: [
        { type: 'raw', sql: 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"' },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('// @dbs:raw:CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
  });

  // --- Table-specific extensions (check, engine, charset, collation) ---

  it('should generate table-specific @dbs extensions after their table', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'users',
          columns: [col()],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
      extensions: [
        { type: 'engine', tableName: 'users', engine: 'InnoDB' },
        { type: 'charset', tableName: 'users', charset: 'utf8mb4' },
        { type: 'collation', tableName: 'users', collation: 'utf8mb4_unicode_ci' },
        { type: 'check', tableName: 'users', name: 'age_check', condition: 'age >= 0' },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('// @dbs:engine:users:InnoDB');
    expect(result).toContain('// @dbs:charset:users:utf8mb4');
    expect(result).toContain('// @dbs:collation:users:utf8mb4_unicode_ci');
    expect(result).toContain('// @dbs:check:users:age_check:age >= 0');
  });

  // --- Multiple tables ---

  it('should generate multiple tables in sequence', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'users',
          columns: [col({ name: 'id' }), { name: 'email', type: 'varchar(255)', nullable: false, primaryKey: false, unique: true, autoIncrement: false }],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
        {
          name: 'posts',
          columns: [col({ name: 'id' }), { name: 'title', type: 'varchar(255)', nullable: false, primaryKey: false, unique: false, autoIncrement: false }],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
    };
    const result = generateDbml(schema);
    const usersIdx = result.indexOf('Table users {');
    const postsIdx = result.indexOf('Table posts {');
    expect(usersIdx).toBeGreaterThan(-1);
    expect(postsIdx).toBeGreaterThan(-1);
    expect(usersIdx).toBeLessThan(postsIdx);
  });

  // --- Identifier escaping ---

  it('should not escape simple alphanumeric identifiers', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [table({ name: 'my_table', columns: [col({ name: 'my_column' })] })],
    };
    const result = generateDbml(schema);
    expect(result).toContain('Table my_table {');
    expect(result).toContain('my_column integer');
  });

  it('should escape identifiers with special characters', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'my table',
          columns: [
            { name: 'my col', type: 'integer', nullable: false, primaryKey: true, unique: false, autoIncrement: false },
          ],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('Table "my table" {');
    expect(result).toContain('"my col" integer');
  });
});

// ============================================================
// Tests: roundtrip (SchemaIR → DBML → parseDbml → SchemaIR)
// ============================================================

describe('roundtrip: SchemaIR → DBML → parseDbml', () => {
  it('should roundtrip a simple table with all column settings', () => {
    const original: SchemaIR = {
      tables: [
        {
          name: 'users',
          columns: [
            { name: 'id', type: 'integer', nullable: false, primaryKey: true, unique: false, autoIncrement: true },
            { name: 'email', type: 'varchar(255)', nullable: false, primaryKey: false, unique: true, autoIncrement: false },
            { name: 'name', type: 'varchar(100)', nullable: false, primaryKey: false, unique: false, autoIncrement: false },
          ],
          indexes: [
            { name: 'idx_email', columns: ['email'], unique: true },
          ],
          foreignKeys: [],
          triggers: [],
        },
      ],
      views: [],
      procedures: [],
      enums: [],
      extensions: [],
    };

    const dbml = generateDbml(original);
    const parsed = parseDbml(dbml);

    expect(parsed.tables).toHaveLength(1);
    expect(parsed.tables[0]!.name).toBe('users');
    expect(parsed.tables[0]!.columns).toHaveLength(3);

    const idCol = parsed.tables[0]!.columns.find(c => c.name === 'id')!;
    expect(idCol.primaryKey).toBe(true);
    expect(idCol.autoIncrement).toBe(true);
    expect(idCol.nullable).toBe(false);

    const emailCol = parsed.tables[0]!.columns.find(c => c.name === 'email')!;
    expect(emailCol.unique).toBe(true);
    expect(emailCol.nullable).toBe(false);

    expect(parsed.tables[0]!.indexes).toHaveLength(1);
    expect(parsed.tables[0]!.indexes[0]!.name).toBe('idx_email');
    expect(parsed.tables[0]!.indexes[0]!.unique).toBe(true);
  });

  it('should roundtrip a table with foreign keys', () => {
    const original: SchemaIR = {
      tables: [
        {
          name: 'posts',
          columns: [
            { name: 'id', type: 'integer', nullable: false, primaryKey: true, unique: false, autoIncrement: true },
            { name: 'user_id', type: 'integer', nullable: false, primaryKey: false, unique: false, autoIncrement: false },
          ],
          indexes: [],
          foreignKeys: [
            {
              name: 'fk_posts_user',
              columns: ['user_id'],
              refTable: 'users',
              refColumns: ['id'],
              onDelete: 'cascade',
            },
          ],
          triggers: [],
        },
        {
          name: 'users',
          columns: [
            { name: 'id', type: 'integer', nullable: false, primaryKey: true, unique: false, autoIncrement: true },
          ],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
      views: [],
      procedures: [],
      enums: [],
      extensions: [],
    };

    const dbml = generateDbml(original);
    const parsed = parseDbml(dbml);

    // FK should be attached to posts table
    const postsTable = parsed.tables.find(t => t.name === 'posts')!;
    expect(postsTable.foreignKeys).toHaveLength(1);
    expect(postsTable.foreignKeys[0]!.columns).toEqual(['user_id']);
    expect(postsTable.foreignKeys[0]!.refTable).toBe('users');
    expect(postsTable.foreignKeys[0]!.onDelete).toBe('cascade');
  });

  it('should roundtrip enums', () => {
    const original: SchemaIR = {
      tables: [],
      views: [],
      procedures: [],
      enums: [
        { name: 'role', values: ['admin', 'editor', 'viewer'] },
      ],
      extensions: [],
    };

    const dbml = generateDbml(original);
    const parsed = parseDbml(dbml);

    expect(parsed.enums).toHaveLength(1);
    expect(parsed.enums[0]!.name).toBe('role');
    expect(parsed.enums[0]!.values).toEqual(['admin', 'editor', 'viewer']);
  });

  it('should roundtrip triggers as @dbs comments', () => {
    const original: SchemaIR = {
      tables: [
        {
          name: 'users',
          columns: [col()],
          indexes: [],
          foreignKeys: [],
          triggers: [
            {
              name: 'after_insert_users',
              timing: 'after',
              event: 'insert',
              body: 'CREATE TRIGGER after_insert_users\nAFTER INSERT ON users\nFOR EACH ROW\nBEGIN\n  INSERT INTO audit_log VALUES (1);\nEND;',
            },
          ],
        },
      ],
      views: [],
      procedures: [],
      enums: [],
      extensions: [],
    };

    const dbml = generateDbml(original);
    const parsed = parseDbml(dbml);

    const usersTable = parsed.tables.find(t => t.name === 'users')!;
    expect(usersTable.triggers).toHaveLength(1);
    expect(usersTable.triggers[0]!.name).toBe('after_insert_users');
    expect(usersTable.triggers[0]!.timing).toBe('after');
    expect(usersTable.triggers[0]!.event).toBe('insert');
    expect(usersTable.triggers[0]!.body).toContain('CREATE TRIGGER after_insert_users');
  });

  it('should roundtrip views as @dbs comments', () => {
    const original: SchemaIR = {
      tables: [],
      views: [
        { name: 'active_users', definition: 'CREATE VIEW active_users AS SELECT id FROM users WHERE active = 1;' },
      ],
      procedures: [],
      enums: [],
      extensions: [],
    };

    const dbml = generateDbml(original);
    const parsed = parseDbml(dbml);

    expect(parsed.views).toHaveLength(1);
    expect(parsed.views[0]!.name).toBe('active_users');
    expect(parsed.views[0]!.definition).toContain('CREATE VIEW active_users');
  });

  it('should roundtrip procedures as @dbs comments', () => {
    const original: SchemaIR = {
      tables: [],
      views: [],
      procedures: [
        { name: 'cleanup', body: 'CREATE PROCEDURE cleanup() BEGIN DELETE FROM logs; END;' },
      ],
      enums: [],
      extensions: [],
    };

    const dbml = generateDbml(original);
    const parsed = parseDbml(dbml);

    expect(parsed.procedures).toHaveLength(1);
    expect(parsed.procedures[0]!.name).toBe('cleanup');
    expect(parsed.procedures[0]!.body).toContain('CREATE PROCEDURE cleanup()');
  });

  it('should roundtrip table-specific extensions', () => {
    const original: SchemaIR = {
      tables: [
        {
          name: 'users',
          columns: [col()],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
      views: [],
      procedures: [],
      enums: [],
      extensions: [
        { type: 'engine', tableName: 'users', engine: 'InnoDB' },
        { type: 'check', tableName: 'users', name: 'age_check', condition: 'age >= 0' },
      ],
    };

    const dbml = generateDbml(original);
    const parsed = parseDbml(dbml);

    const engineExt = parsed.extensions.find(e => e.type === 'engine');
    expect(engineExt).toBeDefined();
    if (engineExt && engineExt.type === 'engine') {
      expect(engineExt.tableName).toBe('users');
      expect(engineExt.engine).toBe('InnoDB');
    }

    const checkExt = parsed.extensions.find(e => e.type === 'check');
    expect(checkExt).toBeDefined();
    if (checkExt && checkExt.type === 'check') {
      expect(checkExt.tableName).toBe('users');
      expect(checkExt.name).toBe('age_check');
      expect(checkExt.condition).toBe('age >= 0');
    }
  });

  it('should roundtrip default values', () => {
    const original: SchemaIR = {
      tables: [
        {
          name: 'test',
          columns: [
            col({ name: 'id' }),
            { name: 'role', type: 'varchar(20)', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: 'user' },
            { name: 'count', type: 'integer', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: '0' },
          ],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
      views: [],
      procedures: [],
      enums: [],
      extensions: [],
    };

    const dbml = generateDbml(original);
    const parsed = parseDbml(dbml);

    const roleCol = parsed.tables[0]!.columns.find(c => c.name === 'role')!;
    // The parser strips DBML quoting from STRING tokens;
    // the IR stores the raw value without quotes.
    expect(roleCol.defaultValue).toBe('user');

    const countCol = parsed.tables[0]!.columns.find(c => c.name === 'count')!;
    expect(countCol.defaultValue).toBe('0');
  });

  it('should roundtrip composite indexes', () => {
    const original: SchemaIR = {
      tables: [
        {
          name: 'users',
          columns: [
            col({ name: 'id' }),
            { name: 'first_name', type: 'varchar(50)', nullable: false, primaryKey: false, unique: false, autoIncrement: false },
            { name: 'last_name', type: 'varchar(50)', nullable: false, primaryKey: false, unique: false, autoIncrement: false },
          ],
          indexes: [
            { name: 'idx_name', columns: ['first_name', 'last_name'], unique: false, type: 'btree' },
          ],
          foreignKeys: [],
          triggers: [],
        },
      ],
      views: [],
      procedures: [],
      enums: [],
      extensions: [],
    };

    const dbml = generateDbml(original);
    const parsed = parseDbml(dbml);

    expect(parsed.tables[0]!.indexes).toHaveLength(1);
    expect(parsed.tables[0]!.indexes[0]!.columns).toEqual(['first_name', 'last_name']);
    expect(parsed.tables[0]!.indexes[0]!.name).toBe('idx_name');
  });

  it('should roundtrip a complete schema matching test.dbml', () => {
    const original: SchemaIR = {
      tables: [
        {
          name: 'users',
          columns: [
            { name: 'id', type: 'integer', nullable: false, primaryKey: true, unique: false, autoIncrement: true },
            { name: 'name', type: 'varchar(100)', nullable: false, primaryKey: false, unique: false, autoIncrement: false },
            { name: 'email', type: 'varchar(255)', nullable: false, primaryKey: false, unique: true, autoIncrement: false },
            { name: 'created_at', type: 'timestamp', nullable: false, primaryKey: false, unique: false, autoIncrement: false, defaultValue: '`now()`' },
          ],
          indexes: [
            { name: 'idx_users_email', columns: ['email'], unique: true },
          ],
          foreignKeys: [],
          triggers: [
            {
              name: 'after_insert_users',
              timing: 'after',
              event: 'insert',
              body: 'CREATE TRIGGER after_insert_users\nAFTER INSERT ON users\nFOR EACH ROW\nBEGIN\n  INSERT INTO audit_log(table_name,record_id,action)\n  VALUES(\'users\',NEW.id,\'INSERT\');\nEND;',
            },
          ],
        },
        {
          name: 'posts',
          columns: [
            { name: 'id', type: 'integer', nullable: false, primaryKey: true, unique: false, autoIncrement: true },
            { name: 'user_id', type: 'integer', nullable: false, primaryKey: false, unique: false, autoIncrement: false },
            { name: 'title', type: 'varchar(255)', nullable: false, primaryKey: false, unique: false, autoIncrement: false },
            { name: 'body', type: 'text', nullable: true, primaryKey: false, unique: false, autoIncrement: false },
          ],
          indexes: [
            { name: 'idx_posts_user_id', columns: ['user_id'], unique: false },
          ],
          foreignKeys: [
            {
              name: 'fk_posts_user',
              columns: ['user_id'],
              refTable: 'users',
              refColumns: ['id'],
              onDelete: 'cascade',
            },
          ],
          triggers: [],
        },
      ],
      views: [
        {
          name: 'active_users',
          definition: 'CREATE VIEW active_users AS\nSELECT u.id,u.name,COUNT(p.id) as post_count\nFROM users u\nLEFT JOIN posts p ON p.user_id=u.id\nGROUP BY u.id,u.name;',
        },
      ],
      procedures: [
        {
          name: 'cleanup_old_posts',
          body: 'CREATE PROCEDURE cleanup_old_posts(IN days_old INT)\nBEGIN\n  DELETE FROM posts WHERE created_at < DATE_SUB(NOW(),INTERVAL days_old DAY);\nEND;',
        },
      ],
      enums: [
        { name: 'user_role', values: ['admin', 'editor', 'viewer'] },
      ],
      extensions: [],
    };

    const dbml = generateDbml(original);
    const parsed = parseDbml(dbml);

    // Tables
    expect(parsed.tables).toHaveLength(2);
    const usersTable = parsed.tables.find(t => t.name === 'users')!;
    const postsTable = parsed.tables.find(t => t.name === 'posts')!;

    // Users columns
    expect(usersTable.columns).toHaveLength(4);
    const idCol = usersTable.columns.find(c => c.name === 'id')!;
    expect(idCol.primaryKey).toBe(true);
    expect(idCol.autoIncrement).toBe(true);

    const emailCol = usersTable.columns.find(c => c.name === 'email')!;
    expect(emailCol.unique).toBe(true);

    // Users index
    expect(usersTable.indexes).toHaveLength(1);
    expect(usersTable.indexes[0]!.name).toBe('idx_users_email');

    // Users trigger
    expect(usersTable.triggers).toHaveLength(1);
    expect(usersTable.triggers[0]!.name).toBe('after_insert_users');

    // Posts FK
    expect(postsTable.foreignKeys).toHaveLength(1);
    expect(postsTable.foreignKeys[0]!.refTable).toBe('users');
    expect(postsTable.foreignKeys[0]!.onDelete).toBe('cascade');

    // Views
    expect(parsed.views).toHaveLength(1);
    expect(parsed.views[0]!.name).toBe('active_users');

    // Procedures
    expect(parsed.procedures).toHaveLength(1);
    expect(parsed.procedures[0]!.name).toBe('cleanup_old_posts');

    // Enums
    expect(parsed.enums).toHaveLength(1);
    expect(parsed.enums[0]!.name).toBe('user_role');
    expect(parsed.enums[0]!.values).toEqual(['admin', 'editor', 'viewer']);
  });
});

// ============================================================
// Tests: helper functions (via public API)
// ============================================================

describe('default value formatting', () => {
  function getDefault(colDef: ColumnDef): string | undefined {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [{ name: 't', columns: [colDef], indexes: [], foreignKeys: [], triggers: [] }],
    };
    const dbml = generateDbml(schema);
    const match = dbml.match(/default:\s*([^\s,\]]+)/);
    return match ? match[1] : undefined;
  }

  it('should format NULL as null', () => {
    const dv = getDefault({ name: 'c', type: 'text', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: 'NULL' });
    expect(dv).toBe('null');
  });

  it('should format lowercase null as null', () => {
    const dv = getDefault({ name: 'c', type: 'text', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: 'null' });
    expect(dv).toBe('null');
  });

  it('should preserve backtick expressions', () => {
    const dv = getDefault({ name: 'c', type: 'timestamp', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: '`now()`' });
    expect(dv).toBe('`now()`');
  });

  it('should format integer defaults without quotes', () => {
    const dv = getDefault({ name: 'c', type: 'integer', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: '42' });
    expect(dv).toBe('42');
  });

  it('should format negative defaults without quotes', () => {
    const dv = getDefault({ name: 'c', type: 'integer', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: '-1' });
    expect(dv).toBe('-1');
  });

  it('should format string defaults in single quotes', () => {
    const dv = getDefault({ name: 'c', type: 'varchar', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: 'hello' });
    expect(dv).toBe("'hello'");
  });

  it('should escape single quotes in default values', () => {
    const dv = getDefault({ name: 'c', type: 'varchar', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: "it's" });
    expect(dv).toBe("'it\\'s'");
  });

  it('should format boolean defaults', () => {
    const dv = getDefault({ name: 'c', type: 'boolean', nullable: true, primaryKey: false, unique: false, autoIncrement: false, defaultValue: 'true' });
    expect(dv).toBe('true');
  });
});

// ============================================================
// Tests: identifier escaping
// ============================================================

describe('identifier escaping', () => {
  it('should not quote simple identifiers', () => {
    const result = generateDbml({
      ...emptySchema(),
      tables: [table({ name: 'abc_123', columns: [col({ name: 'col_a1' })] })],
    });
    expect(result).toContain('Table abc_123 {');
    expect(result).toContain('col_a1 integer');
  });

  it('should quote identifiers with spaces', () => {
    const result = generateDbml({
      ...emptySchema(),
      tables: [
        {
          name: 'my table',
          columns: [
            { name: 'my col', type: 'text', nullable: true, primaryKey: false, unique: false, autoIncrement: false },
          ],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
    });
    expect(result).toContain('Table "my table" {');
    expect(result).toContain('"my col" text');
  });

  it('should escape double quotes inside quoted identifiers', () => {
    const result = generateDbml({
      ...emptySchema(),
      tables: [
        {
          name: 'weird"name',
          columns: [
            { name: 'id', type: 'integer', nullable: false, primaryKey: true, unique: false, autoIncrement: false },
          ],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
    });
    expect(result).toContain('Table "weird\\"name" {');
  });
});

// ============================================================
// Tests: edge cases
// ============================================================

describe('edge cases', () => {
  it('should handle table with no columns gracefully', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [{ name: 'empty_table', columns: [], indexes: [], foreignKeys: [], triggers: [] }],
    };
    const result = generateDbml(schema);
    expect(result).toContain('Table empty_table {');
    expect(result).toContain('}');
  });

  it('should handle column with no explicit type (fallback to varchar)', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'test',
          columns: [
            { name: 'col', type: '', nullable: true, primaryKey: false, unique: false, autoIncrement: false },
          ],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('col varchar');
  });

  it('should handle unique primary key without duplicate unique setting', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'test',
          columns: [
            { name: 'id', type: 'integer', nullable: false, primaryKey: true, unique: true, autoIncrement: false },
          ],
          indexes: [],
          foreignKeys: [],
          triggers: [],
        },
      ],
    };
    const result = generateDbml(schema);
    // Should NOT have both pk and unique
    expect(result).toContain('[pk, not null]');
    expect(result).not.toContain('unique');
  });

  it('should handle trigger with no body', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'users',
          columns: [col()],
          indexes: [],
          foreignKeys: [],
          triggers: [
            { name: 'empty_trigger', timing: 'before', event: 'delete', body: '' },
          ],
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('// @dbs:trigger:empty_trigger:users:before:delete');
  });

  it('should handle view with no definition', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      views: [{ name: 'empty_view', definition: '' }],
    };
    const result = generateDbml(schema);
    expect(result).toContain('// @dbs:view:empty_view');
  });

  it('should handle procedure with no body', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      procedures: [{ name: 'empty_proc', body: '' }],
    };
    const result = generateDbml(schema);
    expect(result).toContain('// @dbs:procedure:empty_proc');
  });

  it('should handle index with btree type (not output type)', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      tables: [
        {
          name: 'users',
          columns: [col()],
          indexes: [
            { name: 'idx1', columns: ['a'], unique: false, type: 'btree' },
          ],
          foreignKeys: [],
          triggers: [],
        },
      ],
    };
    const result = generateDbml(schema);
    expect(result).not.toContain('type: btree');
  });

  it('should handle raw extension with multiline SQL', () => {
    const schema: SchemaIR = {
      ...emptySchema(),
      extensions: [
        { type: 'raw', sql: 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"\nSELECT 1;' },
      ],
    };
    const result = generateDbml(schema);
    expect(result).toContain('// @dbs:raw:CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
    expect(result).toContain('// SELECT 1;');
  });
});
